//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ZyluxCap.rc
//
#define IDR_TYPELIB                     1
#define IDC_PUSH                        2
#define IDC_LOADFILE                    3
#define IDM_ABOUTBOX                    0x0010
#define IDM_SHOWTTY                     0x0020
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_ABOUTBOX                    101
#define IDD_SERIAL                      101
#define IDD_ZYLUXCAP_DIALOG             102
#define IDS_DATA                        102
#define IDR_MAINFRAME                   128
#define IDD_DATAWIN                     129
#define IDD_PP_XFER                     130
#define IDR_SMALLFRAME                  131
#define IDD_PP_DATAWIN                  131
#define IDD_PP_APP                      132
#define IDD_PP_XXX                      133
#define IDD_PP_SERIAL                   133
#define IDR_ZNOTIFY                     136
#define TTYACCEL                        200
#define IDM_CONNECT                     0x100
#define IDM_DISCONNECT                  0x101
#define IDM_EXIT                        0x102
#define IDM_SETTINGS                    0x103
#define IDM_SENDBLOCK                   0x105
#define TTYMENU                         300
#define TTYICON                         400
#define TTYBITMAP                       500
#define IDD_PORTCB                      0x220
#define IDD_BAUDCB                      0x221
#define IDD_DATABITSCB                  0x222
#define IDD_PARITYCB                    0x223
#define IDD_STOPBITSCB                  0x224
#define IDD_DTRDSR                      0x225
#define IDD_RTSCTS                      0x226
#define IDD_XONXOFF                     0x227
#define IDD_AUTOWRAP                    0x228
#define IDD_NEWLINE                     0x229
#define IDD_LOCALECHO                   0x22A
#define IDD_FONT                        0x22B
#define IDD_USECNRECEIVE                0x22C
#define IDD_DISPLAYERRORS               0x22D
#define IDD_AUTOQUIT                    558
#define IDD_AUTOCONNECT                 559
#define IDS_MODE_STANDARD               0x301
#define IDS_MODE_ENHANCED               0x302
#define IDS_MODE_WLO                    0x303
#define IDS_MODE_UNDEF                  0x304
#define IDS_COMPREFIX                   0x310
#define IDS_BAUD110                     0x320
#define IDS_BAUD300                     0x321
#define IDS_BAUD600                     0x322
#define IDS_BAUD1200                    0x323
#define IDS_BAUD2400                    0x324
#define IDS_BAUD4800                    0x325
#define IDS_BAUD9600                    0x326
#define IDS_BAUD14400                   0x327
#define IDS_BAUD19200                   0x328
#define IDS_BAUD38400                   0x329
#define IDS_BAUD56000                   0x32A
#define IDS_BAUD128000                  0x32B
#define IDS_BAUD256000                  0x32C
#define IDS_FLOWCTRL                    813
#define IDS_PARITY                      815
#define IDS_PARITYNONE                  0x330
#define IDS_PARITYEVEN                  0x331
#define IDS_PARITYODD                   0x332
#define IDS_PARITYMARK                  0x333
#define IDS_PARITYSPACE                 0x334
#define IDS_STOPBIT                     0x33f
#define IDS_ONESTOPBIT                  0x340
#define IDS_ONE5STOPBITS                0x341
#define IDS_TWOSTOPBITS                 0x342
#define IDR_ENT_APP                     835
#define IDR_ENT_SETTINGS                836
#define IDR_ENT_DATA                    837
#define IDS_SETTINGS                    838
#define IDS_COMDEV                      839
#define IDS_LOCALECHO                   840
#define IDS_AUTOWRAP                    841
#define IDS_PORTNO                      842
#define IDS_BAUDRATE                    843
#define IDS_XONOFF                      844
#define IDS_BYTESIZE                    845
#define IDS_DISPERRS                    846
#define IDS_TIMEOUT                     847
#define IDS_AUTOCONNECT                 848
#define IDS_AUTOQUIT                    849
#define ID_INDICATOR_CLOCK              850
#define IDS_SPECFILE                    851
#define IDS_SPECSHEET                   852
#define IDS_SPECRANGE                   853
#define IDS_NAMEFILE                    854
#define IDS_NAMERANGEROW                855
#define IDS_NAMESHEET                   856
#define IDS_NAMERANGECOL                857
#define IDS_REPFILE                     858
#define IDC_CHK_CONNECT                 1000
#define IDC_TTYDATA                     1001
#define IDC_SLDDELAY                    1004
#define IDC_DELTIME                     1005
#define IDC_EDT_RANGEROW                1007
#define IDC_EDT_FILE                    1008
#define IDC_CHK_RANGE                   1009
#define IDC_CHK_FILE                    1010
#define IDC_EDT_SHEET                   1011
#define IDC_CHK_SHEET                   1012
#define IDC_EDT_RANGECOL                1013
#define IDC_CHK_REPFILE                 1014
#define IDC_ERRMSG                      1015
#define IDC_APPNAME                     1016
#define IDC_VERINFO                     1017

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1017
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
