//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ZyluxZip.rc
//
#define IDC_PUSH                        2
#define IDC_LOADFILE                    3
#define IDM_ABOUTBOX                    0x0010
#define IDM_SHOWDATA                    0x0020
#define IDP_OLE_INIT_FAILED             100
#define IDS_ABOUTBOX                    101
#define IDD_ZYLUXZIP_DIALOG             102
#define IDR_ENT_APP                     102
#define IDD_ABOUTBOX                    103
#define IDR_ENT_SETTINGPS               103
#define IDR_ZYLUXZIP                    104
#define IDR_ENT_DATA                    104
#define IDR_ENT_TTY                     105
#define IDD_PP_APP                      108
#define IDD_PP_SERIAL                   109
#define IDD_PP_DATAWIN                  110
#define IDR_MAINFRAME                   128
#define IDD_DATAWIN                     129
#define IDD_SITELIST                    130
#define IDR_ZYLTYPE                     130
#define IDD_NAMELIST                    131
#define IDS_TTYSETTINGS                 131
#define IDD_RUN_PROTOCOL                132
#define IDS_SETTINGS                    132
#define IDS_APPSETTINGS                 132
#define IDS_DATA                        133
#define IDS_AUTOWRAP                    134
#define IDS_DISPERRS                    135
#define IDS_TEXTCOLOR                   136
#define IDS_NEWLINE                     137
#define IDS_HEXMODE                     138
#define IDR_MENU_CONTEXT                140
#define IDC_PORTCB                      0x220
#define IDC_BAUDCB                      0x221
#define IDC_DATABITSCB                  0x222
#define IDC_PARITYCB                    0x223
#define IDC_STOPBITSCB                  0x224
#define IDC_DTRDSR                      0x225
#define IDC_RTSCTS                      0x226
#define IDC_XONXOFF                     0x227
#define IDC_AUTOWRAP                    0x228
#define IDC_NEWLINE                     0x229
#define IDC_LOCALECHO                   0x22A
#define IDC_FONT                        0x22B
#define IDC_DISPLAYERRORS               0x22D
#define IDS_COMPREFIX                   0x310
#define IDS_BAUD110                     0x320
#define IDS_BAUD300                     0x321
#define IDS_BAUD600                     0x322
#define IDS_BAUD1200                    0x323
#define IDS_BAUD2400                    0x324
#define IDS_BAUD4800                    0x325
#define IDS_BAUD9600                    0x326
#define IDS_BAUD14400                   0x327
#define IDS_BAUD19200                   0x328
#define IDS_BAUD38400                   0x329
#define IDS_BAUD56000                   0x32A
#define IDS_BAUD128000                  0x32B
#define IDS_BAUD256000                  0x32C
#define IDS_FLOWCTRL                    813
#define IDS_PARITY                      815
#define IDS_PARITYNONE                  0x330
#define IDS_PARITYEVEN                  0x331
#define IDS_PARITYODD                   0x332
#define IDS_PARITYMARK                  0x333
#define IDS_PARITYSPACE                 0x334
#define IDS_STOPBIT                     0x33f
#define IDS_ONESTOPBIT                  0x340
#define IDS_ONE5STOPBITS                0x341
#define IDS_TWOSTOPBITS                 0x342
#define IDS_COMDEV                      839
#define IDS_LOCALECHO                   840
#define IDS_PORTNO                      842
#define IDS_BAUDRATE                    843
#define IDS_XONOFF                      844
#define IDS_BYTESIZE                    845
#define IDS_CURRENT_SLOT                846
#define IDS_AUTOCONNECT                 848
#define IDC_SITELIST                    1000
#define IDS_FONTHEIGHT                  1000
#define IDC_TTYDATA                     1001
#define IDS_FONTWIDTH                   1001
#define IDS_FONTWEIGHT                  1002
#define IDS_FONTITALIC                  1003
#define IDS_FONTPITCH                   1004
#define IDS_FONTNAME                    1005
#define IDC_LIST_EDIT                   1009
#define IDC_LIST_SAVE                   1011
#define IDC_LIST_PRINT                  1012
#define IDC_LIST_SEND                   1013
#define IDC_VERINFO                     1014
#define IDC_DLG_TITLE                   1015
#define IDC_RUN_ASSEMBLY                1016
#define IDC_RUN_NAME                    1017
#define IDC_SITE_COUNT                  1018
#define IDC_NEEDNAMES                   1019
#define IDC_EDIT                        1020
#define IDC_RUN_SLOT                    1021
#define IDC_HEXMODE                     1022
#define IDC_APPNAME                     2000
#define IDC_COPYRIGHT                   2001
#define IDC_CHECK_CELL                  5000
#define IDM_SITELIST                    32772
#define IDM_RUN_NAMES                   32773
#define IDM_RUN_PROTOCOL                32774
#define IDM_SETTINGS                    32775
#define IDM_SEND_DATA                   32776
#define IDM_CAPTURE                     32777
#define IDM_RUN_PROTOCOL_OPEN           32778
#define IDM_RUN_PROTOCOL_NEW            32779
#define ID_EDIT_DEL_ROW                 32780
#define ID_EDIT_INS_ROW                 32781
#define ID_EDIT_SELECTALL               32782
#define IDM_RUN_PROTOCOL_DELETE         32783

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32785
#define _APS_NEXT_CONTROL_VALUE         1023
#define _APS_NEXT_SYMED_VALUE           112
#endif
#endif
