//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MK.rc
//
#define IDC_BROWSE                      3
#define IDD_ABOUTBOX                    100
#define IDD_MKVIEW                      101
#define IDD_RUNVIEW                     102
#define IDR_MAINFRAME                   128
#define IDR_MKTYPE                      129
#define IDR_MKVIEWTYPE                  130
#define IDB_RUNBAR                      131
#define IDS_FB12_CONTROL_FAILED         131
#define IDR_KINETICSFRAME               131
#define IDS_FB12_EVENTS_FAILED          132
#define IDD_MKEDIT                      132
#define IDS_FB12_ADVISE_FAILED          133
#define IDR_FB12                        133
#define IDS_FB12_SERIAL_FAILED          134
#define IDS_FB12_TIMEOUT                135
#define IDS_FB12_ERROR_INIT             136
#define IDR_MEASURE                     136
#define IDS_FB12_ERROR_GENERAL          137
#define IDR_VIEWFRAME                   137
#define IDS_FB12_ERROR_CHECKSUM         138
#define IDR_CONTEXT                     138
#define IDS_MEASUREMESSAGE              139
#define IDB_EDITPIC                     139
#define IDS_FB12_DOOROPENED             140
#define IDD_EXCELOPTIONS                140
#define IDS_DELAYMESSAGE                141
#define IDS_OUTOFTIME                   142
#define IDS_OLE_INIT_FAILED             143
#define IDS_VIEW_IDLEMESSAGE            144
#define IDR_MKKINETICSTYPE              145
#define IDD_MKADVANCED                  146
#define IDR_MKKINETICSVIEWTYPE          146
#define IDW_RUNBAR                      501
#define IDW_FB12BAR                     502
#define IDD_PPSDIALOG                   801
#define IDD_GRAPHVIEW                   802
#define IDD_GRAPHOPTVIEW                803
#define IDC_MKGRID                      1000
#define PPS_IDC_STATIC_PROTOCOLS        1000
#define IDC_STATIC_DATE                 1001
#define PPS_IDC_LIST_PROTOCOLS          1001
#define IDC_EDIT_DATE                   1002
#define PPS_IDC_STATIC_PROTOCOL         1002
#define IDC_STATIC_TIME                 1003
#define PPS_IDC_EDIT_PROTOCOL           1003
#define IDC_EDIT_TIME                   1004
#define IDC_SAVE                        1006
#define IDC_SAVEAS                      1007
#define IDC_EDIT_MEASTIME               1008
#define IDC_STATIC_DELAYTIMESEC         1009
#define IDC_STATIC_MEASTIMESEC          1010
#define IDC_STATIC_INTERVAL             1011
#define IDC_STATIC_MEAS                 1012
#define IDC_EDIT_DELAY                  1013
#define IDC_SPIN_DELAY                  1014
#define IDC_EDIT_MEAS                   1015
#define IDC_SPIN_MEAS                   1016
#define IDC_SPIN_DURATIONMIN            1017
#define IDC_EDIT_INTERVAL               1018
#define IDC_STATIC_DURATION             1020
#define IDC_EDIT_DURATION               1021
#define IDC_SPIN_SAMPS                  1022
#define IDC_EDIT_SAMPS                  1023
#define IDC_STATIC_NUMREP               1024
#define IDC_EDIT_NUMREP                 1025
#define IDC_SPIN_NUMREP                 1026
#define IDC_COMBO_XFORM                 1027
#define IDC_STATIC_XFORM                1028
#define IDC_COMBO_ORDER                 1029
#define IDC_STATIC_ORDER                1030
#define IDC_STATIC_NUMSAMP              1031
#define IDC_EDIT_NUMSAMP                1032
#define IDC_SPIN_NUMSAMP                1033
#define IDC_RADIO_STARTBUTTON           1035
#define IDC_RADIO_DOORCLOSE             1036
#define IDC_STATIC_COMMENT              1037
#define IDC_EDIT_COMMENT                1038
#define IDC_CHECK_BACKGROUND            1039
#define IDC_CHECK_TIMESTAMPS            1040
#define IDC_STATIC_MACRO                1041
#define IDC_EDIT_MACRO                  1042
#define IDC_ADVANCED                    1043
#define IDC_EXCEL                       1043
#define IDC_EDIT_COMMENTS               1044
#define IDC_STATIC_BACKGROUND           1045
#define IDC_CHECK_NORMALIZE             1046
#define IDC_STATIC_RLUS                 1047
#define IDC_GB_TIMES                    1048
#define IDC_EDIT_NORMALIZE              1049
#define IDC_STATIC_RLUS2                1050
#define IDC_EDIT_BACKGROUND             1051
#define IDC_STATIC_RLUS3                1052
#define IDC_CHART                       1053
#define IDC_CHECK_SMOOTHING             1054
#define IDC_CHECK_LOG                   1055
#define IDC_RADIO_AUTOMATIC             1057
#define IDC_RADIO_MANUAL                1058
#define IDC_EDIT_MIN                    1059
#define IDC_EDIT_MAX                    1060
#define IDC_LIST_REPLICATES             1063
#define IDC_STATIC1_COL1                1066
#define IDC_STATIC1_COL2                1067
#define IDC_STATIC2_COL2                1068
#define IDC_STATIC1_COL3                1069
#define IDC_STATIC2_COL3                1070
#define IDC_STATIC1_COL4                1071
#define IDC_STATIC1_COL5                1072
#define IDC_STATIC2_COL5                1073
#define IDC_STATIC1_COL6                1074
#define IDC_STATIC2_COL6                1075
#define IDC_RADIO_NOMINAL               1076
#define IDC_SPIN_DURATIONSEC            1077
#define IDC_RADIO_ACTUAL                1077
#define IDC_CHECK_AUTOSEND              1077
#define IDC_SPIN_REPS                   1078
#define IDC_STATIC_RLURANGE             1078
#define IDC_STATIC_DELAYTIME            1079
#define IDC_EDIT_WORKBOOK               1079
#define IDC_EDIT_DELAYTIME              1080
#define IDC_STATIC_MEASTIME             1081
#define IDC_EDIT_WORKSHEET              1081
#define IDC_STATIC_INTERVALTIME         1082
#define IDC_COMBO_COL                   1082
#define IDC_STATIC_DELAY                1083
#define IDC_EDIT_ROW                    1083
#define IDC_EDIT_INTERVALTIME           1084
#define IDC_STATIC_DURATIONTIME         1085
#define IDC_STATIC_NUMSAMPS             1086
#define IDC_EDIT_DURATIONTIME           1087
#define IDC_EDIT_REPS                   1088
#define IDC_STATIC_COMMENTS             1089
#define IDC_STATIC_NUMMEAS              1090
#define IDC_EDIT_NUMMEAS                1091
#define IDC_SPIN_NUMMEAS                1092
#define IDC_CHECK_TIMEBASE              1093
#define IDC_STATIC_MACNAME              1094
#define IDC_EDIT_MACNAME                1095
#define IDC_STATIC_PROGICON             1096
#define IDC_GB_ANALYTES                 1097
#define IDC_CB_ALLOWNONNOMINAL          1098
#define IDC_STATIC_PROGSTR              1099
#define IDC_CB_TIMEBASE                 1100
#define IDC_STATIC_VERSION              1100
#define IDC_STATIC_NUMREPS              1101
#define ID_VIEW_RUNBAR                  32771
#define ID_FILE_SAVEASTEXT              32772
#define ID_FILE_SAVE_AS_TEXT            32773
#define ID_EXCEL                        32774
#define ID_FB12_DOOR                    32775
#define ID_MEASURE_START                32776
#define ID_MEASURE_STOP                 32777
#define ID_MEASURE_DELETE               32778
#define ID_MEASURE_KINETICS             32779
#define ID_KINETICS_ZOOMOUT             32780
#define ID_CONTEXT_BACKGROUND           32785
#define ID_FILE_SAVE_KINETICS_AS_TEXT   32786
#define ID_MEASURE_GRID                 32790
#define ID_FB12_DOORSTATUS              32800
#define ID_FB12_TIMER                   32801
#define ID_FB12_RX                      32802
#define ID_FB12_COUNTER                 32803

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32801
#define _APS_NEXT_CONTROL_VALUE         1079
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
