//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SA.rc
//
#define IDC_BROWSE                      3
#define IDD_ABOUTBOX                    100
#define IDD_SAVIEW                      101
#define IDD_RUNVIEW                     102
#define IDR_MAINFRAME                   128
#define IDR_SATYPE                      129
#define IDR_SAVIEWTYPE                  130
#define IDB_RUNBAR                      131
#define IDP_FB12_CONTROL_FAILED         131
#define IDS_FB12_CONTROL_FAILED         131
#define IDR_KINETICSFRAME               131
#define IDP_FB12_EVENTS_FAILED          132
#define IDS_FB12_EVENTS_FAILED          132
#define IDD_SAEDIT                      132
#define IDP_FB12_ADVISE_FAILED          133
#define IDS_FB12_ADVISE_FAILED          133
#define IDD_SAADVANCED                  133
#define IDR_FB12                        133
#define IDS_FB12_SERIAL_FAILED          134
#define IDS_FB12_TIMEOUT                135
#define IDS_FB12_ERROR_INIT             136
#define IDR_MEASURE                     136
#define IDS_FB12_ERROR_GENERAL          137
#define IDR_VIEWFRAME                   137
#define IDS_FB12_ERROR_CHECKSUM         138
#define IDR_CONTEXT                     138
#define IDS_MEASUREMESSAGE              139
#define IDS_FB12_DOOROPENED             140
#define IDD_EXCELOPTIONS                140
#define IDS_DELAYMESSAGE                141
#define IDS_OUTOFTIME                   142
#define IDS_OLE_INIT_FAILED2            143
#define IDS_VIEW_IDLEMESSAGE            144
#define IDR_DAVIEWTYPE                  145
#define IDR_SAKINETICSTYPE              146
#define IDW_RUNBAR                      501
#define IDW_FB12BAR                     502
#define IDD_PPSDIALOG                   801
#define IDC_SAGRID                      1000
#define PPS_IDC_STATIC_PROTOCOLS        1000
#define IDC_STATIC_DATE                 1001
#define PPS_IDC_LIST_PROTOCOLS          1001
#define IDC_EDIT_DATE                   1002
#define PPS_IDC_STATIC_PROTOCOL         1002
#define IDC_STATIC_TIME                 1003
#define PPS_IDC_EDIT_PROTOCOL           1003
#define IDC_EDIT_TIME                   1004
#define IDC_STATIC_DELAYTIME            1005
#define IDC_EDIT_DELAYTIME              1006
#define IDC_SAVE                        1006
#define IDC_STATIC_MEASTIME             1007
#define IDC_SAVEAS                      1007
#define IDC_EDIT_MEASTIME               1008
#define IDC_STATIC_DELAYTIMESEC         1009
#define IDC_EDIT_NUMREPS                1009
#define IDC_STATIC_MEASTIMESEC          1010
#define IDC_STATIC_DELAY                1010
#define IDC_STATIC_NUMREPS              1010
#define IDC_STATIC_REPS                 1011
#define IDC_STATIC_NUMSAMPS             1011
#define IDC_STATIC_MEAS                 1012
#define IDC_EDIT_NUMSAMPS               1012
#define IDC_EDIT_DELAY                  1013
#define IDC_EDIT_BACKGROUND             1013
#define IDC_SPIN_DELAY                  1014
#define IDC_STATIC_BACKGROUND           1014
#define IDC_EDIT_MEAS                   1015
#define IDC_STATIC_RLUs                 1015
#define IDC_SPIN_MEAS                   1016
#define IDC_EDIT_REPS                   1017
#define IDC_ADVANCED                    1018
#define IDC_SPIN_REPS                   1019
#define IDC_STATIC_SAMPS                1020
#define IDC_EDIT_SAMPS                  1021
#define IDC_SPIN_SAMPS                  1022
#define IDC_CB_TIMESTAMP                1023
#define IDC_EXCEL                       1023
#define IDC_CB_BACKGROUND               1024
#define IDC_GB_OPTIONS                  1025
#define IDC_STATIC_COMMENTS             1025
#define IDC_CB_95CONFCOL                1026
#define IDC_CB_FLEXREPS                 1027
#define IDC_CB_99CONFCOL                1028
#define IDC_CB_FLEXSAMPS                1029
#define IDC_RB_DOORCLOSE                1030
#define IDC_GB_STARTOPTION              1031
#define IDC_RB_STARTBUTTON              1032
#define IDC_GB_SAMPTITLES               1033
#define IDC_EDIT_DEFAULTSAMP            1034
#define IDC_GB_ENTRYORDER               1034
#define IDC_EDGRID                      1035
#define IDC_STATIC_DEFAULT              1036
#define IDC_RB_ROWORDER                 1036
#define IDC_CLEAR                       1037
#define IDC_IMPORT                      1038
#define IDC_STATIC_SPECIFIED            1039
#define IDC_DELETE                      1039
#define IDC_STATIC_MACNAME              1040
#define IDC_EDIT_MACNAME                1041
#define IDC_ADDREP                      1042
#define IDC_RB_COLORDER                 1042
#define IDC_EDIT_MACRO                  1042
#define IDC_ADDSAMP                     1043
#define IDC_EDIT_COMMENTS               1043
#define IDC_DELMEAS                     1044
#define IDC_STATIC_GROUP                1044
#define IDC_EDIT_GROUP                  1045
#define IDC_STATIC_PROGICON             1045
#define IDC_STATIC_PROGSTR              1046
#define IDC_GB_TIMES                    1047
#define IDC_STATIC_VERSION              1047
#define IDC_GB_REPSAMPS                 1048
#define IDC_CHECK_AUTOSEND              1077
#define IDC_EDIT_WORKBOOK               1079
#define IDC_EDIT_WORKSHEET              1081
#define IDC_COMBO_COL                   1082
#define IDC_EDIT_ROW                    1083
#define ID_VIEW_RUNBAR                  32771
#define ID_FILE_SAVEASTEXT              32772
#define ID_FILE_SAVE_AS_TEXT            32773
#define ID_EXCEL                        32774
#define ID_FB12_DOOR                    32775
#define ID_MEASURE_START                32776
#define ID_MEASURE_STOP                 32777
#define ID_MEASURE_DELETE               32778
#define ID_MEASURE_KINETICS             32779
#define ID_FILE_SAVE_KINETICS_AS_TEXT   32780
#define ID_MEASURE_GRID                 32781
#define ID_CONTEXT_BACKGROUND           32782
#define ID_KINETICS_ZOOMOUT             32785
#define ID_FB12_DOORSTATUS              32800
#define ID_FB12_TIMER                   32801
#define ID_FB12_RX                      32802
#define IDC_BUTTON_START                33000
#define IDC_BUTTON_STOP                 33001
#define IDC_CHECK_KINETICS              33002
#define IDC_BUTTON_DELETE               33003

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32792
#define _APS_NEXT_CONTROL_VALUE         1049
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
